name: CI

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - '*'

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    env:
      GOPRIVATE: "github.com/machbase/*"
      PKGNAME: "booter"
    steps:
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.6'
      - name: Build
        run: go test .