name: CI

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - '*'

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20' ]
    env:
      PKGNAME: "booter"
    steps:
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.6'
      - name: Test
        run: go test -v